spring.application.name=livehh-engine

#Postgres
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=admin
spring.datasource.password=adminpassword
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.properties.hibernate.default_schema=public

#Hibernate
spring.jpa.hibernate.ddl-auto=update

#Logs
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true